/**
 * Created by YikaJ on 16/5/6.
 */


export const GET_DEVICE_DATA_REQUEST = 'GET_DEVICE_DATA_REQUEST'

/*
  User entities
 */
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

/*
  Device
 */

// 更新设备数据
export const UPDATE_DEVICE_DATA = 'UPDATE_DEVICE_DATA'

// 获取设备列表
export const GET_DEVICE_REQUEST = 'GET_DEVICE_REQUEST'
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS'
export const GET_DEVICE_FAILURE = 'GET_DEVICE_FAILURE'

// 新增设备
export const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST'
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS'
export const ADD_DEVICE_FAILURE = 'ADD_DEVICE_FAILURE'

// 发送绑定码
export const POST_BIND_CODE_REQUEST = 'POST_BIND_CODE_REQUEST'
export const POST_BIND_CODE_SUCCESS = 'POST_BIND_CODE_SUCCESS'
export const POST_BIND_CODE_FAILURE = 'POST_BIND_CODE_FAILURE'

// 清空注册设备的相关信息
export const CLEAR_DEVICE_FORM = 'CLEAR_DEVICE_FORM'

// 直接进入设备绑定界面
export const START_TO_BIND_DEVICE = 'START_TO_BIND_DEVICE'


/*
  Data 数据界面
 */
// 内部导航
export const CHART_DATA_NAV_TO = 'CHART_DATA_NAV_TO'

// 获取历史趋势数据
export const GET_HISTORY_DATA_REQUEST = 'GET_HISTORY_DATA_REQUEST'
export const GET_HISTORY_DATA_SUCCESS = 'GET_HISTORY_DATA_SUCCESS'
export const GET_HISTORY_DATA_FAILURE = 'GET_HISTORY_DATA_FAILURE'

// 改变图表
export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE'