/**
 * Created by YikaJ on 16/5/6.
 */


export const GET_DEVICE_DATA_REQUEST = 'GET_DEVICE_DATA_REQUEST'

/*
  User entities
 */
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

/*
  Device
 */

// 获取设备列表
export const GET_DEVICE_REQUEST = 'GET_DEVICE_REQUEST'
export const GET_DEVICE_SUCCESS = 'GET_DEVICE_SUCCESS'
export const GET_DEVICE_FAILURE = 'GET_DEVICE_FAILURE'

// 新增设备
export const ADD_DEVICE_REQUEST = 'ADD_DEVICE_REQUEST'
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS'
export const ADD_DEVICE_FAILURE = 'ADD_DEVICE_FAILURE'

// 发送绑定码
export const POST_BIND_CODE_REQUEST = 'POST_BIND_CODE_REQUEST'
export const POST_BIND_CODE_SUCCESS = 'POST_BIND_CODE_SUCCESS'
export const POST_BIND_CODE_FAILURE = 'POST_BIND_CODE_FAILURE'